name: whisper
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - openssl=3.5.4
  - pip=25.2
  - python=3.11.14
  - setuptools=80.9.0
  - tk=8.6.13
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - pip:
      - aiofiles==24.1.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - brotli==1.1.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - fastapi==0.120.0
      - ffmpy==0.6.4
      - filelock==3.20.0
      - fsspec==2025.9.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - llvmlite==0.45.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - networkx==3.5
      - numba==0.62.1
      - numpy==2.3.3
      - openai-whisper==20250625
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.2.0
      - ruff==0.14.2
      - safehttpx==0.1.7
      - semantic-version==2.10.0
      - setuptools-rust==1.12.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.48.0
      - sympy==1.14.0
      - tiktoken==0.12.0
      - tomlkit==0.13.3
      #- torch==2.8.0+cu129
      #- torchvision==0.23.0+cu129
      - tqdm==4.67.1
      #- triton-windows==3.5.0.post21
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - websockets==15.0.1
      - yt-dlp==2025.10.22
prefix: C:\Users\dev\miniconda3\envs\whisper
